package confluence

import (
	"regexp"

	"github.com/pmarschik/adfast/adf"
	"github.com/pmarschik/adfast/ast"
	"github.com/pmarschik/adfast/extension"
)

// The parameters codec of the sugared macros: the ADF parameters blob
//
//	{"macroParams":  {"maxLevel": {"value": "3"}, "": {"value": "Page"}},
//	 "macroMetadata":{"macroId": {"value": "…"},
//	                  "schemaVersion": {"value": "1"},
//	                  "title": "Table of Contents"}}
//
// ⇄ directive attributes, with the unnamed parameter ("" — how the
// include and excerpt-include macros carry their target page) as the
// directive label.
//
// Everything under macroMetadata is derived, not authored:
//
//   - macroId is generated by Confluence. A page written with no macroId
//     at all comes back with one filled in (verified on a live page,
//     2026-07-29, both with and without macroMetadata present), and both
//     macros rendered normally, so the id never needs to live in the
//     markdown.
//   - schemaVersion and title are constant per macro key, so the spec
//     table supplies them on encode and decode drops them. A value that
//     diverges from the table survives as an explicit attribute, so a
//     future schema bump is carried rather than silently rewritten.
//
// The codec is deliberately strict: any shape it cannot represent
// exactly — a non-string parameter, an unexpected metadata field, a
// parameter named like one of the reserved attributes — makes the decode
// hooks decline the node, and it degrades through the generic
// ::extension directive with its parameters JSON intact.

// attrNameRe is the directive attribute name grammar (micromark's
// directive extension): a parameter whose name does not fit cannot be
// written as an attribute.
var attrNameRe = regexp.MustCompile(`^[A-Za-z_:][A-Za-z0-9_.:-]*$`)

// reservedMacroAttrs are the directive attributes that carry ADF node
// fields or macro metadata rather than macro parameters. A macro
// parameter by one of these names would be ambiguous, so the decode
// declines it (no core macro has one).
var reservedMacroAttrs = map[string]bool{
	"layout":        true,
	"localId":       true,
	"schemaVersion": true,
	"title":         true,
}

// macroParameters builds the ADF parameters blob from the directive
// attributes and label. macroParams is always present (Confluence writes
// it even when empty); macroMetadata carries the spec defaults unless an
// attribute overrides them.
func macroParameters(spec macroSpec, attrs map[string]string, label string) any {
	params := map[string]any{}
	if label != "" {
		params[""] = map[string]any{"value": label}
	}
	for name, value := range attrs {
		if reservedMacroAttrs[name] {
			continue
		}
		params[name] = map[string]any{"value": value}
	}
	schemaVersion := spec.schemaVersion
	if v, ok := attrs["schemaVersion"]; ok {
		schemaVersion = v
	}
	title := spec.title
	if v, ok := attrs["title"]; ok {
		title = v
	}
	return map[string]any{
		"macroParams": params,
		"macroMetadata": map[string]any{
			"schemaVersion": map[string]any{"value": schemaVersion},
			"title":         title,
		},
	}
}

// macroFields is one decoded macro: the directive name, its attributes
// and its label (the unnamed parameter).
type macroFields struct {
	attrs map[string]string
	name  string
	label string
}

// macroSugar converts one ADF extension node's fields to the sugared
// directive form, reporting false when the macro is not one of the
// sugared keys or carries anything the directive form cannot hold — in
// which case the caller declines the node and the generic ::extension
// path takes it.
func macroSugar(key, text, layout, localID string, extra map[string]any, parameters any) (macroFields, bool) {
	name, known := macroNames[key]
	if !known || text != "" || len(extra) > 0 {
		return macroFields{}, false
	}
	params, meta, ok := macroSections(parameters)
	if !ok {
		return macroFields{}, false
	}
	f := macroFields{name: name, attrs: map[string]string{}}
	if f.label, ok = readMacroParams(params, f.attrs); !ok {
		return macroFields{}, false
	}
	if !readMacroMetadata(meta, macroSpecs[name], f.attrs) {
		return macroFields{}, false
	}
	// "default" IS the layout default: Confluence writes it on some
	// macros and omits it on others, so an omitted layout round-trips.
	if layout != "" && layout != "default" {
		f.attrs["layout"] = layout
	}
	if localID != "" {
		f.attrs["localId"] = localID
	}
	return f, true
}

// macroSections splits the parameters blob into its two known sections;
// an unknown section (or a non-object shape) is not representable.
func macroSections(parameters any) (params, meta map[string]any, ok bool) {
	if parameters == nil {
		return nil, nil, true
	}
	root, isMap := parameters.(map[string]any)
	if !isMap {
		return nil, nil, false
	}
	for key, value := range root {
		section, isSection := value.(map[string]any)
		if !isSection {
			return nil, nil, false
		}
		switch key {
		case "macroParams":
			params = section
		case "macroMetadata":
			meta = section
		default:
			return nil, nil, false
		}
	}
	return params, meta, true
}

// readMacroParams copies the macro parameters into directive attributes
// and returns the unnamed one as the label.
func readMacroParams(params map[string]any, attrs map[string]string) (label string, ok bool) {
	for name, raw := range params {
		value, isString := macroParamValue(raw)
		if !isString {
			return "", false
		}
		if name == "" {
			// An empty label would not survive the round trip (the
			// renderer writes no [] for it), so keep the generic form.
			if value == "" {
				return "", false
			}
			label = value
			continue
		}
		if reservedMacroAttrs[name] || !attrNameRe.MatchString(name) {
			return "", false
		}
		attrs[name] = value
	}
	return label, true
}

// macroParamValue reads a {"value": "…"} wrapper.
func macroParamValue(raw any) (string, bool) {
	wrapper, ok := raw.(map[string]any)
	if !ok || len(wrapper) != 1 {
		return "", false
	}
	value, isString := wrapper["value"].(string)
	return value, isString
}

// readMacroMetadata drops the derived metadata and keeps only values
// that diverge from the macro's spec defaults.
func readMacroMetadata(meta map[string]any, spec macroSpec, attrs map[string]string) bool {
	for key, raw := range meta {
		switch key {
		case "macroId":
			// Server-generated; dropped (see the package comment above).
			if _, ok := macroParamValue(raw); !ok {
				return false
			}
		case "schemaVersion":
			value, ok := macroParamValue(raw)
			if !ok {
				return false
			}
			if value != spec.schemaVersion {
				attrs["schemaVersion"] = value
			}
		case "title":
			value, isString := raw.(string)
			if !isString {
				return false
			}
			if value != spec.title {
				attrs["title"] = value
			}
		default:
			return false
		}
	}
	return true
}

// decodeMacroBlock decodes the block macro forms: a bodiless extension
// to the ::name leaf directive, a bodiedExtension to the :::name
// container. Unsugared keys decline and degrade to ::extension.
func decodeMacroBlock(n adf.Node, ctx extension.DecodeContext) (ast.Node, bool) {
	switch ext := n.(type) {
	case *adf.Extension:
		if ext.ExtensionType != MacroExtensionType {
			return nil, false
		}
		f, ok := macroSugar(ext.ExtensionKey, ext.Text, ext.Layout, ext.LocalID, ext.Extra, ext.Parameters)
		if !ok {
			return nil, false
		}
		return &Macro{Name: f.name, Attrs: f.attrs, Children: labelText(f.label)}, true
	case *adf.BodiedExtension:
		if ext.ExtensionType != MacroExtensionType {
			return nil, false
		}
		f, ok := macroSugar(ext.ExtensionKey, ext.Text, ext.Layout, ext.LocalID, ext.Extra, ext.Parameters)
		if !ok {
			return nil, false
		}
		children := ctx.DecodeBlocks(ext.Content)
		if f.label != "" {
			children = append([]ast.Node{&ast.Paragraph{
				DirectiveLabel: true,
				Children:       []ast.Node{&ast.Text{Value: f.label}},
			}}, children...)
		}
		return &BodiedMacro{Name: f.name, Attrs: f.attrs, Children: children}, true
	}
	return nil, false
}

// decodeMacroInline decodes the inline macro form (inlineExtension) to
// the :name text directive.
func decodeMacroInline(n adf.Node, _ extension.DecodeContext) ([]ast.Node, bool) {
	ext, ok := n.(*adf.InlineExtension)
	if !ok || ext.ExtensionType != MacroExtensionType {
		return nil, false
	}
	f, sugared := macroSugar(ext.ExtensionKey, ext.Text, "", ext.LocalID, ext.Extra, ext.Parameters)
	if !sugared {
		return nil, false
	}
	return []ast.Node{&InlineMacro{Name: f.name, Attrs: f.attrs, Children: labelText(f.label)}}, true
}

// labelText is the label's inline content ({} for no label).
func labelText(label string) []ast.Node {
	if label == "" {
		return nil
	}
	return []ast.Node{&ast.Text{Value: label}}
}
