package assets

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/pmarschik/adfast/convert"
)

// mustCatalog returns the enumeration face of a store, failing when it
// has none.
func mustCatalog(t *testing.T, s Store) Catalog {
	t.Helper()
	c, ok := CatalogOf(s)
	if !ok {
		t.Fatal("store has no catalog")
	}
	return c
}

// recordFor picks the record for a friendly name out of an inventory.
func recordFor(t *testing.T, recs []Record, name string) Record {
	t.Helper()
	for _, r := range recs {
		if r.Name == name {
			return r
		}
	}
	t.Fatalf("no record named %q in %d records", name, len(recs))
	return Record{}
}

// TestRecordsListsContentWithoutAMediaID pins the reason Catalog exists:
// Assets is keyed by media id, so content the store holds but no upload
// has been through is missing from it. An inventory has to name it.
func TestRecordsListsContentWithoutAMediaID(t *testing.T) {
	dir := t.TempDir()
	s := mustStore(t, dir)
	mustAdd(t, s, "media-1", "shot.png", []byte("uploaded bytes"))
	if _, err := s.Put("chart.svg", []byte("generated bytes")); err != nil {
		t.Fatal(err)
	}

	if got := len(s.Assets()); got != 1 {
		t.Errorf("Assets() has %d entries, want 1 — only the uploaded one", got)
	}
	recs := mustCatalog(t, s).Records()
	if len(recs) != 2 {
		t.Fatalf("Records() has %d entries, want 2: %+v", len(recs), recs)
	}

	shot := recordFor(t, recs, "shot.png")
	if len(shot.IDs) != 1 || shot.IDs[0].ID != "media-1" {
		t.Errorf("shot.png ids = %+v, want one media-1", shot.IDs)
	}
	chart := recordFor(t, recs, "chart.svg")
	if len(chart.IDs) != 0 {
		t.Errorf("chart.svg ids = %+v, want none — it was never uploaded", chart.IDs)
	}
	if chart.Hash != ContentHash([]byte("generated bytes")) {
		t.Errorf("chart.svg hash = %q, want the content hash", chart.Hash)
	}
}

// TestRecordsAreSortedByHash pins the order, because an inventory that
// reorders between runs cannot be diffed.
func TestRecordsAreSortedByHash(t *testing.T) {
	s := mustStore(t, t.TempDir())
	for _, body := range []string{"one", "two", "three", "four"} {
		if _, err := s.Put(body+".txt", []byte(body)); err != nil {
			t.Fatal(err)
		}
	}
	recs := mustCatalog(t, s).Records()
	for i := 1; i < len(recs); i++ {
		if recs[i-1].Hash >= recs[i].Hash {
			t.Fatalf("records out of order at %d: %q then %q", i, recs[i-1].Hash, recs[i].Hash)
		}
	}
}

// TestRecordsNamesTheBlobAndItsSize pins that an inventory can reach the
// content it describes, which is what makes it usable for a check.
func TestRecordsNamesTheBlobAndItsSize(t *testing.T) {
	dir := t.TempDir()
	s := mustSplitStore(t, dir, mustMkdir(t, filepath.Join(dir, "docs")), WithStoreDir(".asset-store"))
	content := []byte("some bytes of picture")
	mustAdd(t, s, "media-1", "shot.png", content)

	rec := recordFor(t, mustCatalog(t, s).Records(), "shot.png")
	if rec.Size != int64(len(content)) {
		t.Errorf("size = %d, want %d", rec.Size, len(content))
	}
	if want := filepath.Join(dir, ".asset-store", rec.Hash+".png"); rec.Blob != want {
		t.Errorf("blob = %q, want %q", rec.Blob, want)
	}
	got, err := os.ReadFile(rec.Blob)
	if err != nil || !bytes.Equal(got, content) {
		t.Errorf("reading the named blob: %q, err %v", got, err)
	}
}

// TestRecordsReportsAMissingBlob pins the one integrity answer an
// inventory owes: a record describing content nothing can show is still
// listed, and says so by naming no blob.
func TestRecordsReportsAMissingBlob(t *testing.T) {
	dir := t.TempDir()
	s := mustStore(t, dir)
	mustAdd(t, s, "media-1", "shot.png", []byte("picture"))

	rec := recordFor(t, mustCatalog(t, s).Records(), "shot.png")
	mustDo(t, os.Remove(rec.Blob))

	rec = recordFor(t, mustCatalog(t, s).Records(), "shot.png")
	if rec.Blob != "" || rec.Size != 0 {
		t.Errorf("blob = %q (%d bytes), want none after the file was removed", rec.Blob, rec.Size)
	}
}

// TestRecordsFindsABlobTheNameNoLongerPredicts pins why the blob
// directory is read instead of each file name derived. A blob is named
// for the extension the friendly name had when the content was first
// stored, and the friendly name can be changed afterwards — by hand, or
// by an embedder renaming what it generated. Deriving would then report
// content that is sitting right there as content the store lost.
func TestRecordsFindsABlobTheNameNoLongerPredicts(t *testing.T) {
	dir := t.TempDir()
	s := mustStore(t, dir)
	mustAdd(t, s, "media-1", "picture.png", []byte("picture"))
	hash := ContentHash([]byte("picture"))

	blobs := filepath.Join(dir, Dir, ".store")
	mustDo(t, os.Rename(filepath.Join(blobs, hash+".png"), filepath.Join(blobs, hash+".svg")))

	rec := recordFor(t, mustCatalog(t, s).Records(), "picture.png")
	if want := filepath.Join(blobs, hash+".svg"); rec.Blob != want {
		t.Errorf("blob = %q, want %q", rec.Blob, want)
	}
}

// TestRecordsCarriesMetadataAndCopiesIt pins that an inventory reports
// the embedder's namespaces, and that what it hands back is the
// caller's: a report that could edit the index by writing to a map it
// was given would be a surprising way to lose provenance.
func TestRecordsCarriesMetadataAndCopiesIt(t *testing.T) {
	s := mustStore(t, t.TempDir())
	mustAdd(t, s, "media-1", "chart.svg", []byte("drawn"))
	hash := ContentHash([]byte("drawn"))
	mustDo(t, s.SetMeta(hash, "diagram", json.RawMessage(`{"lang":"d2"}`)))

	rec := recordFor(t, mustCatalog(t, s).Records(), "chart.svg")
	if string(rec.Meta["diagram"]) != `{"lang":"d2"}` {
		t.Fatalf("diagram meta = %q, want the recorded value", rec.Meta["diagram"])
	}

	delete(rec.Meta, "diagram")
	if _, ok := s.Meta(hash, "diagram"); !ok {
		t.Error("deleting from the returned map reached the store")
	}
}

// TestLayeredCatalogReportsEachContentOnce pins the merge: layers over
// one shared index all know every record, and an inventory that repeated
// them would count one asset as several.
func TestLayeredCatalogReportsEachContentOnce(t *testing.T) {
	root := t.TempDir()
	one := mustSplitStore(t, root, mustMkdir(t, filepath.Join(root, "one")))
	two := mustSplitStore(t, root, mustMkdir(t, filepath.Join(root, "two")))
	mustAdd(t, one, "media-1", "shot.png", []byte("picture"))

	recs := mustCatalog(t, Layered(one, two)).Records()
	if len(recs) != 1 {
		t.Fatalf("layered inventory has %d records, want 1: %+v", len(recs), recs)
	}
	if recs[0].Name != "shot.png" {
		t.Errorf("record name = %q, want shot.png", recs[0].Name)
	}
}

// TestLayeredCatalogUnionsDistinctStores pins the other half: layers that
// are not the same store contribute what only they hold.
func TestLayeredCatalogUnionsDistinctStores(t *testing.T) {
	one := mustStore(t, t.TempDir())
	two := mustStore(t, t.TempDir())
	mustAdd(t, one, "media-1", "one.png", []byte("first"))
	mustAdd(t, two, "media-2", "two.png", []byte("second"))

	recs := mustCatalog(t, Layered(one, two)).Records()
	if len(recs) != 2 {
		t.Fatalf("layered inventory has %d records, want 2: %+v", len(recs), recs)
	}
	recordFor(t, recs, "one.png")
	recordFor(t, recs, "two.png")
}

// TestScopedCatalogKeepsEveryMediaID pins the pass-through: a view bound
// to one container still reports that the content is attached in
// another, because "in use elsewhere" is exactly what an inventory is
// asked for.
func TestScopedCatalogKeepsEveryMediaID(t *testing.T) {
	dir := t.TempDir()
	s := mustStore(t, dir)
	content := []byte("picture")
	mustDo(t, mustErr(s.Add("PROJ-1", "media-1", "shot.png", content)))
	mustDo(t, mustErr(s.Add("PROJ-2", "media-2", "shot.png", content)))

	view := ForScope(s, "PROJ-1")
	if _, ok := MetaOf(view); !ok {
		t.Error("a scoped view of a store with metadata lost its metadata face")
	}
	rec := recordFor(t, mustCatalog(t, view).Records(), "shot.png")
	if len(rec.IDs) != 2 {
		t.Fatalf("scoped inventory ids = %+v, want both", rec.IDs)
	}
	if _, ok := view.Lookup("", "assets/shot.png"); !ok {
		t.Error("the scoped view stopped resolving its own scope")
	}
}

// mustErr drops the asset a store write returns so the error can go
// through mustDo. (Go will not forward a two-valued call into a
// one-argument one.)
func mustErr(_ convert.MediaAsset, err error) error { return err }

// TestCatalogOfAStoreWithoutOne pins that a store which cannot be
// enumerated says so, rather than answering with an empty inventory that
// reads as "nothing is in here".
func TestCatalogOfAStoreWithoutOne(t *testing.T) {
	if _, ok := CatalogOf(bareStore{}); ok {
		t.Error("CatalogOf claimed a store that keeps no inventory")
	}
	if _, ok := CatalogOf(Layered(bareStore{}, bareStore{})); ok {
		t.Error("CatalogOf claimed a stack with no enumerable layer")
	}
	if _, ok := CatalogOf(ForScope(bareStore{}, "PROJ-1")); ok {
		t.Error("CatalogOf claimed a scoped view of a store with no inventory")
	}
}

// bareStore is the minimum Store: no metadata, no inventory.
type bareStore struct{}

func (bareStore) Resolve(string) (convert.MediaAsset, bool) { return convert.MediaAsset{}, false }
func (bareStore) Lookup(string, string) (string, bool)      { return "", false }
func (bareStore) Assets() map[string]convert.MediaAsset     { return nil }
func (bareStore) Pending(string) ([]string, error)          { return nil, nil }
func (bareStore) Load(string) ([]byte, error)               { return nil, os.ErrNotExist }
func (bareStore) Dims(string) (width, height int, ok bool)  { return 0, 0, false }

func (bareStore) Add(string, string, string, []byte) (convert.MediaAsset, error) {
	return convert.MediaAsset{}, os.ErrInvalid
}

func (bareStore) Associate(string, string, string) (convert.MediaAsset, error) {
	return convert.MediaAsset{}, os.ErrInvalid
}
