// Command genemoji generates dialect's JoyPixels shortname lookup table.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"
)

const sourceURL = "https://raw.githubusercontent.com/joypixels/emoji-toolkit/245bb1bf82b411e1bbe51d5c2da8e62dc6c789c6/emoji.json"

type emoji struct {
	Shortname  string `json:"shortname"`
	CodePoints struct {
		FullyQualified string `json:"fully_qualified"`
	} `json:"code_points"`
	ShortnameAlternates []string `json:"shortname_alternates"`
}

func main() {
	output := flag.String("output", "emoji_map.go", "generated Go file")
	flag.Parse()

	entries, err := loadEntries()
	if err != nil {
		log.Fatal(err)
	}
	generated, err := render(entries)
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*output, generated, 0o600); err != nil {
		log.Fatal(err)
	}
}

func loadEntries() (map[string]string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, sourceURL, http.NoBody)
	if err != nil {
		return nil, fmt.Errorf("create emoji data request: %w", err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("download emoji data: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("download emoji data: %s", resp.Status)
	}

	const maxSourceSize = 16 << 20
	data, err := io.ReadAll(io.LimitReader(resp.Body, maxSourceSize+1))
	if err != nil {
		return nil, fmt.Errorf("read emoji data: %w", err)
	}
	if len(data) > maxSourceSize {
		return nil, fmt.Errorf("emoji data exceeds %d bytes", maxSourceSize)
	}

	var source map[string]emoji
	if err := json.Unmarshal(data, &source); err != nil {
		return nil, fmt.Errorf("decode emoji data: %w", err)
	}

	entries := make(map[string]string)
	for _, item := range source {
		unicode, err := decodeCodePoints(item.CodePoints.FullyQualified)
		if err != nil {
			return nil, fmt.Errorf("decode %q: %w", item.Shortname, err)
		}
		for _, name := range append([]string{item.Shortname}, item.ShortnameAlternates...) {
			if name == "" {
				continue
			}
			if previous, exists := entries[name]; exists && previous != unicode {
				return nil, fmt.Errorf("conflicting values for %q", name)
			}
			entries[name] = unicode
		}
	}
	return entries, nil
}

func decodeCodePoints(value string) (string, error) {
	var decoded strings.Builder
	for point := range strings.SplitSeq(value, "-") {
		value, err := strconv.ParseInt(point, 16, 32)
		if err != nil {
			return "", fmt.Errorf("parse code point %q: %w", point, err)
		}
		decoded.WriteRune(rune(value))
	}
	return decoded.String(), nil
}

func render(entries map[string]string) ([]byte, error) {
	names := make([]string, 0, len(entries))
	for name := range entries {
		names = append(names, name)
	}
	sort.Strings(names)

	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by internal/genemoji from JoyPixels emoji.json; DO NOT EDIT.")
	fmt.Fprintln(&output, "package dialect")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "// EmojiUnicode resolves an ADF emoji shortName (\":smile:\") to its")
	fmt.Fprintln(&output, "// unicode rendering; ok is false for custom/site emojis and unknown")
	fmt.Fprintln(&output, "// names (the :emoji directive form carries those).")
	fmt.Fprintln(&output, "func EmojiUnicode(shortName string) (string, bool) {")
	fmt.Fprintln(&output, "\tv, ok := emojiShortnames[shortName]")
	fmt.Fprintln(&output, "\treturn v, ok")
	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "var emojiShortnames = map[string]string{")
	for _, name := range names {
		fmt.Fprintf(&output, "\t%s: %s,\n", strconv.QuoteToASCII(name), strconv.QuoteToASCII(entries[name]))
	}
	fmt.Fprintln(&output, "}")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}
